// muOS .muxupd Builder - Main Application
// Targets MustardOS 2606.0 Andromeda. System data (MUOS_SYSTEMS, MUOS_VERSION)
// comes from systems.js, generated by tools/gen-systems.py.

// State management
const state = {
  sdCard: "sd1", // 'sd1' or 'sd2'
  basePath: "/mnt/mmc",
  files: {
    roms: [],
    bios: [],
    saves: [],
    states: [],
    themes: [],
    applications: [],
    catalogue: [],
    music: [],
    screenshots: [],
    config: [],
  },
  romFolder: "", // Folder under ROMS/ for newly added ROMs
  catalogueSystem: "", // Folder under MUOS/info/catalogue/ for newly added artwork
  catalogueType: "box",
};

// Path mapping
const PATH_MAP = {
  sd1: "/mnt/mmc",
  sd2: "/mnt/sdcard",
};

// Each function receives the stored fileData so per-file choices (ROM folder,
// catalogue system) are kept even if the selection changes afterwards
const CATEGORY_PATHS = {
  roms: (f) => `${state.basePath}/ROMS/${f.romFolder}`,
  bios: () => `${state.basePath}/MUOS/bios`,
  saves: () => `${state.basePath}/MUOS/save/file`,
  states: () => `${state.basePath}/MUOS/save/state`,
  themes: () => `${state.basePath}/MUOS/theme`,
  applications: () => `${state.basePath}/MUOS/application`,
  catalogue: (f) =>
    `${state.basePath}/MUOS/info/catalogue/${f.catalogue}/${f.catalogueType}`,
  music: () => `${state.basePath}/MUOS/music`,
  screenshots: () => `${state.basePath}/MUOS/screenshot`,
  // RetroArch configs live on the system partition, not the SD card
  config: () => "/opt/muos/share/info/config",
};

// Themes and applications are folders named after the theme/app, so a dropped
// folder keeps its name unless it is just the parent container
const KEEP_TOP_FOLDER = {
  themes: ["theme", "themes"],
  applications: ["application", "applications", "app", "apps"],
};

// Packed archives muOS used to extract itself. Inside a .muxupd they would just
// be copied, so they are unpacked here to the layout muOS extracts them to.
const PACKED_ARCHIVES = {
  themes: { ext: ".muxthm", folderPerArchive: true }, // MUOS/theme/<name>/
  applications: { ext: ".muxapp", folderPerArchive: false }, // already contains <App>/
};

// Catalogue folders muOS creates besides the per-system ones (script/system/catalogue.sh)
const CATALOGUE_EXTRA_DIRS = [
  "Application",
  "Archive",
  "Collection",
  "Folder",
  "Root",
  "Task",
  "Theme",
];

// Limits enforced by SAFE_ARCHIVE in muOS script/var/zip.sh - archives over
// any of them are rejected outright by the Archive Manager
const ARCHIVE_LIMITS = {
  maxEntries: 16384,
  maxEntryBytes: 512 * 1024 * 1024,
  maxTotalBytes: 2 * 1024 * 1024 * 1024,
};
// Headroom so rounding or a long manifest never tips an archive over the limit
const PART_SAFETY_BYTES = 8 * 1024 * 1024;

// muOS verifies updates over 256 MiB file-by-file with `unzip -p <name>`, which
// treats these characters as wildcards and fails to find the file. Smaller
// updates are verified by extracting to /tmp first, which handles any name.
const WILDCARD_CHARS = /[[\]*?]/;
const WILDCARD_PART_BYTES = 128 * 1024 * 1024;

const MANIFEST_NAME = "manifest.sha256";
const utf8 = new TextEncoder();
const BIOS_MD5_MAX_BYTES = 64 * 1024 * 1024;

// Known BIOS files by lowercase basename, from the muOS core manifests
const KNOWN_BIOS = new Map();
MUOS_SYSTEMS.forEach((system) => {
  system.bios.forEach(({ file, md5 }) => {
    const key = file.split("/").pop().toLowerCase();
    if (!KNOWN_BIOS.has(key)) KNOWN_BIOS.set(key, []);
    KNOWN_BIOS.get(key).push({ path: file, md5, system: system.name });
  });
});

// Utility functions
function formatBytes(bytes) {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function getTotalFileCount() {
  return Object.values(state.files).reduce(
    (total, files) => total + files.length,
    0,
  );
}

function getTotalFileSize() {
  let total = 0;
  Object.values(state.files).forEach((files) => {
    files.forEach((fileData) => (total += fileData.size));
  });
  return total;
}

function findSystemByFolder(folder) {
  const name = folder.toLowerCase();
  return MUOS_SYSTEMS.find(
    (s) => s.folder === name || s.friendly.includes(name),
  );
}

// Folder names go straight into archive paths, so keep them to one safe
// segment without the wildcard characters muOS can't verify (WILDCARD_CHARS)
function sanitizeFolderName(name) {
  return name
    .trim()
    .replace(/[\\/[\]*?]/g, "_")
    .replace(/^\.+$/, "");
}

// muOS rejects archives with absolute paths, '..' segments or backslashes
function sanitizeRelativePath(path) {
  return path
    .split("/")
    .map((part) => part.replace(/\\/g, "_"))
    .filter((part) => part && part !== "." && part !== "..")
    .join("/");
}

function getZipPath(category, fileData) {
  return `${CATEGORY_PATHS[category](fileData)}/${fileData.relativePath}`.replace(
    /^\//,
    "",
  );
}

// Storage location selection
function initSDCardSelection() {
  const buttons = {
    sd1: document.getElementById("sd1-btn"),
    sd2: document.getElementById("sd2-btn"),
  };
  const currentPathEl = document.querySelector("#current-path span");
  const sd2Note = document.getElementById("sd2-note");

  Object.entries(buttons).forEach(([card, btn]) => {
    btn.addEventListener("click", () => {
      state.sdCard = card;
      state.basePath = PATH_MAP[card];
      Object.values(buttons).forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      currentPathEl.textContent = state.basePath;
      sd2Note.classList.toggle("hidden", card !== "sd2");
      updatePreview();
    });
  });
}

// Fill a <select> with systems grouped like the muOS core manifest
function populateSystemSelect(select, valueKey, extraOptions = []) {
  const groups = new Map();
  MUOS_SYSTEMS.forEach((system) => {
    if (!groups.has(system.group)) groups.set(system.group, []);
    groups.get(system.group).push(system);
  });

  extraOptions.forEach(({ value, label }) => {
    select.add(new Option(label, value));
  });

  [...groups.keys()].sort().forEach((group) => {
    const optgroup = document.createElement("optgroup");
    optgroup.label = group;
    groups.get(group).forEach((system) => {
      const label =
        valueKey === "folder"
          ? `${system.name} (${system.folder})`
          : system.name;
      optgroup.appendChild(new Option(label, system[valueKey]));
    });
    select.appendChild(optgroup);
  });
}

// ROM system selection handler
function initROMSystemSelection() {
  const systemSelect = document.getElementById("rom-system");
  const customInput = document.getElementById("rom-system-custom");

  populateSystemSelect(systemSelect, "folder", [
    { value: "custom", label: "Custom Folder Name" },
  ]);
  systemSelect.value = "nes";
  state.romFolder = "nes";

  systemSelect.addEventListener("change", (e) => {
    if (e.target.value === "custom") {
      customInput.classList.remove("hidden");
      state.romFolder = sanitizeFolderName(customInput.value);
    } else {
      customInput.classList.add("hidden");
      state.romFolder = e.target.value;
    }
    updateRomSystemInfo();
  });

  customInput.addEventListener("input", (e) => {
    state.romFolder = sanitizeFolderName(e.target.value);
    updateRomSystemInfo();
  });

  updateRomSystemInfo();
}

// Show which folder names muOS recognises and which BIOS files the system uses
function updateRomSystemInfo() {
  const info = document.getElementById("rom-system-info");
  const folderEl = document.getElementById("rom-folder-path");
  folderEl.textContent = `ROMS/${state.romFolder || "…"}/`;

  const system = state.romFolder ? findSystemByFolder(state.romFolder) : null;
  if (!system) {
    info.innerHTML = state.romFolder
      ? `<p class="text-amber-400">muOS does not recognise this folder name, so you will need to assign a core to it on the device.</p>`
      : `<p class="text-amber-400">Enter a folder name to add ROMs.</p>`;
    return;
  }

  const aliases = system.friendly
    .filter((f) => f !== state.romFolder)
    .sort((a, b) => a.length - b.length || a.localeCompare(b));
  let html = `<p>Auto-detected by muOS as <span class="text-gray-200">${escapeHtml(system.name)}</span>.</p>`;
  if (aliases.length > 0) {
    html += `<p class="mt-1">Other recognised folder names: <span class="font-mono">${escapeHtml(aliases.slice(0, 12).join(", "))}${aliases.length > 12 ? ", …" : ""}</span></p>`;
  }
  if (system.bios.length > 0) {
    const added = new Set(state.files.bios.map((f) => f.relativePath));
    const items = system.bios
      .filter((b, i, all) => all.findIndex((o) => o.file === b.file) === i)
      .map((b) => {
        const have = added.has(b.file);
        return `<span class="bios-chip ${have ? "bios-chip-ok" : ""}">${have ? "✓ " : ""}${escapeHtml(b.file)}</span>`;
      })
      .join(" ");
    html += `<p class="mt-2">BIOS files this system can use (add them under BIOS Files):</p><div class="mt-1 flex flex-wrap gap-1">${items}</div>`;
  }
  info.innerHTML = html;
}

// Catalogue (artwork) selection handlers
function initCatalogueSelection() {
  const systemSelect = document.getElementById("catalogue-system");
  const typeSelect = document.getElementById("catalogue-type");

  populateSystemSelect(
    systemSelect,
    "catalogue",
    CATALOGUE_EXTRA_DIRS.map((dir) => ({ value: dir, label: `muOS: ${dir}` })),
  );
  systemSelect.value = "Nintendo NES - Famicom";
  state.catalogueSystem = systemSelect.value;

  const updatePath = () => {
    document.getElementById("catalogue-path").textContent =
      `MUOS/info/catalogue/${state.catalogueSystem}/${state.catalogueType}/`;
  };

  systemSelect.addEventListener("change", (e) => {
    state.catalogueSystem = e.target.value;
    updatePath();
  });

  typeSelect.addEventListener("change", (e) => {
    state.catalogueType = e.target.value;
    updatePath();
  });

  updatePath();
}

// File upload handlers
function initUploadZones() {
  const uploadZones = document.querySelectorAll(".upload-zone");

  uploadZones.forEach((zone) => {
    const category = zone.dataset.category;
    const fileInput = zone.querySelector(".file-input");
    const folderInput = zone.querySelector(".folder-input");
    const uploadBtn = zone.querySelector(".upload-btn");
    const folderBtn = zone.querySelector(".folder-btn");
    const fileListEl = zone.parentElement.querySelector(".file-list");

    // Click to upload files
    uploadBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      e.preventDefault();
      fileInput.click();
    });

    // Click to upload folder
    folderBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      e.preventDefault();
      folderInput.click();
    });

    // File and folder input change
    [fileInput, folderInput].forEach((input) => {
      input.addEventListener("change", (e) => {
        const files = Array.from(e.target.files).map((file) => ({
          file,
          relativePath: file.webkitRelativePath || file.name,
        }));
        addFiles(category, files, fileListEl);
        e.target.value = ""; // Reset input
      });
    });

    // Drag and drop with folder support
    zone.addEventListener("dragover", (e) => {
      e.preventDefault();
      zone.classList.add("drag-over");
    });

    zone.addEventListener("dragleave", () => {
      zone.classList.remove("drag-over");
    });

    zone.addEventListener("drop", async (e) => {
      e.preventDefault();
      zone.classList.remove("drag-over");

      // Handle both files and folders
      const items = e.dataTransfer.items;
      if (items) {
        const files = await getAllFilesFromDrop(items);
        if (files.length > 0) {
          addFiles(category, files, fileListEl);
        }
      } else {
        // Fallback for browsers that don't support items
        const files = Array.from(e.dataTransfer.files).map((file) => ({
          file,
          relativePath: file.name,
        }));
        addFiles(category, files, fileListEl);
      }
    });
  });
}

// Helper functions for drag-and-drop folder support
async function getAllFilesFromDrop(items) {
  const files = [];
  const entries = [];

  // Collect all entries
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    if (item.kind === "file") {
      const entry = item.webkitGetAsEntry();
      if (entry) {
        entries.push(entry);
      }
    }
  }

  // Process all entries
  for (const entry of entries) {
    const entryFiles = await getFilesFromEntry(entry);
    files.push(...entryFiles);
  }

  return files;
}

async function getFilesFromEntry(entry, path = "") {
  const files = [];

  if (entry.isFile) {
    // Get the file
    const file = await new Promise((resolve, reject) => {
      entry.file(resolve, reject);
    });
    // Add relative path metadata
    files.push({
      file: file,
      relativePath: path ? `${path}/${file.name}` : file.name,
    });
  } else if (entry.isDirectory) {
    // Read directory contents (must call readEntries multiple times)
    const reader = entry.createReader();
    let allEntries = [];

    // Keep reading until we get all entries
    while (true) {
      const entries = await new Promise((resolve, reject) => {
        reader.readEntries(resolve, reject);
      });

      if (entries.length === 0) {
        break; // No more entries
      }

      allEntries.push(...entries);
    }

    // Recursively process directory contents
    for (const childEntry of allEntries) {
      const newPath = path ? `${path}/${entry.name}` : entry.name;
      const childFiles = await getFilesFromEntry(childEntry, newPath);
      files.push(...childFiles);
    }
  }

  return files;
}

// Work out where a picked or dropped file goes inside its category folder.
// relativePath still includes the top-level folder the user picked/dropped.
function normalizePath(category, relativePath) {
  const parts = sanitizeRelativePath(relativePath).split("/");
  if (parts.length < 2) return parts.join("/");

  const top = parts[0].toLowerCase();
  const withoutTop = parts.slice(1).join("/");

  if (category === "roms") {
    // Strip the system folder if it is one muOS recognises for the selected system
    const system = findSystemByFolder(state.romFolder);
    const names = system ? [system.folder, ...system.friendly] : [];
    names.push(state.romFolder.toLowerCase());
    return names.includes(top) ? withoutTop : parts.join("/");
  }

  if (KEEP_TOP_FOLDER[category]) {
    return KEEP_TOP_FOLDER[category].includes(top)
      ? withoutTop
      : parts.join("/");
  }

  // For other categories, strip the first folder level so a dragged
  // 'bios' or 'music' folder doesn't create an extra nested level
  return withoutTop;
}

// Unpack a .muxthm/.muxapp into individual files at the paths muOS would use
async function expandPackedArchive(category, file) {
  const { folderPerArchive } = PACKED_ARCHIVES[category];
  const baseName = file.name.replace(/\.[^.]+$/, "");
  const reader = new zip.ZipReader(new zip.BlobReader(file));
  const results = [];

  try {
    const entries = await reader.getEntries();
    for (const entry of entries) {
      if (entry.directory) continue;
      // Skip entries muOS would refuse to extract (absolute paths or '..')
      const name = entry.filename.replace(/\\/g, "/");
      if (/^\/|^[A-Za-z]:|(^|\/)\.\.(\/|$)/.test(name)) continue;
      const path = sanitizeRelativePath(name);
      if (!path) continue;

      const blob = await entry.getData(new zip.BlobWriter());
      results.push({
        file: new File([blob], path.split("/").pop()),
        relativePath: folderPerArchive ? `${baseName}/${path}` : path,
        source: file.name,
      });
    }
  } finally {
    await reader.close();
  }

  return results;
}

async function addFiles(category, filesWithPaths, fileListEl) {
  if (category === "roms" && !state.romFolder) {
    alert("Enter a folder name for these ROMs first.");
    return;
  }

  const packed = PACKED_ARCHIVES[category];
  const prepared = [];
  const errors = [];

  for (const { file, relativePath } of filesWithPaths) {
    if (packed && file.name.toLowerCase().endsWith(packed.ext)) {
      try {
        prepared.push(...(await expandPackedArchive(category, file)));
      } catch (error) {
        console.error(`Could not unpack ${file.name}:`, error);
        errors.push(file.name);
      }
      continue;
    }

    const finalPath = normalizePath(category, relativePath);
    if (finalPath) prepared.push({ file, relativePath: finalPath });
  }

  prepared.forEach(({ file, relativePath, source }) => {
    const fileData = {
      file: file,
      name: file.name,
      size: file.size,
      relativePath: relativePath,
    };
    if (source) fileData.source = source;

    // Store the destination with the file so later selection changes don't move it
    if (category === "roms") {
      fileData.romFolder = state.romFolder;
    } else if (category === "catalogue") {
      fileData.catalogue = state.catalogueSystem;
      fileData.catalogueType = state.catalogueType;
    }

    // Check if a file already exists at the same destination
    const zipPath = getZipPath(category, fileData);
    const exists = state.files[category].some(
      (f) => getZipPath(category, f) === zipPath,
    );

    if (!exists) {
      state.files[category].push(fileData);
      if (category === "bios") checkBios(fileData, fileListEl);
    }
  });

  if (errors.length > 0) {
    alert(
      `Could not unpack: ${errors.join(", ")}\n\nMake sure these are valid ${packed.ext} files.`,
    );
  }

  renderFileList(category, fileListEl);
  updatePreview();
  updateGenerateButton();
  if (category === "bios") updateRomSystemInfo();
}

// Compare BIOS files against the names and hashes muOS expects
async function checkBios(fileData, fileListEl) {
  const known = KNOWN_BIOS.get(fileData.name.toLowerCase());
  if (!known) return;

  const atPath = known.filter((k) => k.path === fileData.relativePath);
  if (atPath.length === 0) {
    fileData.biosStatus = {
      level: "warn",
      text: `muOS expects bios/${known[0].path}`,
    };
    renderFileList("bios", fileListEl);
    return;
  }

  const hashes = atPath.map((k) => k.md5).filter(Boolean);
  const systems = [...new Set(atPath.map((k) => k.system))].join(", ");
  if (hashes.length === 0 || fileData.size > BIOS_MD5_MAX_BYTES) {
    fileData.biosStatus = { level: "ok", text: systems };
    renderFileList("bios", fileListEl);
    return;
  }

  const md5 = await hashFile(fileData.file, hashwasm.createMD5);
  fileData.biosStatus = hashes.includes(md5)
    ? { level: "ok", text: `${systems} (verified)` }
    : { level: "warn", text: `Unknown dump - ${systems} expects a different MD5` };
  renderFileList("bios", fileListEl);
}

function renderFileList(category, fileListEl) {
  fileListEl.innerHTML = "";

  if (state.files[category].length === 0) {
    return;
  }

  const header = document.createElement("div");
  header.className = "file-list-header";
  header.innerHTML = `
            <span>${state.files[category].length} file(s)</span>
            <button class="clear-btn" data-category="${category}">Clear all</button>
        `;
  fileListEl.appendChild(header);

  state.files[category].forEach((fileData, index) => {
    const fileItem = document.createElement("div");
    fileItem.className = "file-item";
    if (fileData.size > ARCHIVE_LIMITS.maxEntryBytes) {
      fileItem.classList.add("file-item-error");
    }

    let prefix = "";
    if (category === "roms") prefix = `${fileData.romFolder}/`;
    if (category === "catalogue") {
      prefix = `${fileData.catalogue}/${fileData.catalogueType}/`;
    }
    const displayPath = prefix + (fileData.relativePath || fileData.name);

    let badge = "";
    if (fileData.biosStatus) {
      badge = `<span class="file-badge file-badge-${fileData.biosStatus.level}" title="${escapeHtml(fileData.biosStatus.text)}">${fileData.biosStatus.level === "ok" ? "✓" : "!"} ${escapeHtml(fileData.biosStatus.text)}</span>`;
    } else if (fileData.size > ARCHIVE_LIMITS.maxEntryBytes) {
      badge = `<span class="file-badge file-badge-error">Over 512 MB</span>`;
    }

    fileItem.innerHTML = `
            <span class="file-name" title="${escapeHtml(displayPath)}">${escapeHtml(displayPath)}</span>
            ${badge}
            <span class="file-size">${formatBytes(fileData.size)}</span>
            <button class="remove-btn" data-category="${category}" data-index="${index}">Remove</button>
        `;
    fileListEl.appendChild(fileItem);
  });

  // Add remove button handlers
  fileListEl.querySelectorAll(".remove-btn").forEach((btn) => {
    btn.addEventListener("click", (e) => {
      const category = e.target.dataset.category;
      const index = parseInt(e.target.dataset.index);
      removeFile(category, index, fileListEl);
    });
  });

  fileListEl.querySelector(".clear-btn").addEventListener("click", () => {
    state.files[category] = [];
    renderFileList(category, fileListEl);
    updatePreview();
    updateGenerateButton();
    if (category === "bios") updateRomSystemInfo();
  });
}

function removeFile(category, index, fileListEl) {
  state.files[category].splice(index, 1);
  renderFileList(category, fileListEl);
  updatePreview();
  updateGenerateButton();
  if (category === "bios") updateRomSystemInfo();
}

// Split files into archives muOS will accept (see ARCHIVE_LIMITS)
function planArchives() {
  const items = [];
  const seen = new Set();

  Object.entries(state.files).forEach(([category, files]) => {
    files.forEach((fileData) => {
      const zipPath = getZipPath(category, fileData);
      if (seen.has(zipPath)) return;
      seen.add(zipPath);
      items.push({ fileData, zipPath });
    });
  });

  const oversized = items.filter(
    (item) => item.fileData.size > ARCHIVE_LIMITS.maxEntryBytes,
  );
  const wildcardTooBig = items.filter(
    (item) =>
      WILDCARD_CHARS.test(item.zipPath) &&
      item.fileData.size <= ARCHIVE_LIMITS.maxEntryBytes &&
      item.fileData.size > WILDCARD_PART_BYTES,
  );
  const blocked = new Set([...oversized, ...wildcardTooBig]);

  const parts = [];
  const pack = (list, maxBytes) => {
    let current = null;
    list.forEach((item) => {
      // Every file also adds a "<sha256>  <path>\n" line to the manifest
      const manifestLine = 64 + 2 + utf8.encode(item.zipPath).length + 1;
      const cost = item.fileData.size + manifestLine;
      if (
        !current ||
        current.items.length + 1 >= ARCHIVE_LIMITS.maxEntries ||
        current.bytes + cost > maxBytes
      ) {
        current = { items: [], bytes: 0 };
        parts.push(current);
      }
      current.items.push(item);
      current.bytes += cost;
    });
  };

  const usable = items.filter((item) => !blocked.has(item));
  pack(
    usable.filter((item) => !WILDCARD_CHARS.test(item.zipPath)),
    ARCHIVE_LIMITS.maxTotalBytes - PART_SAFETY_BYTES,
  );
  const regularParts = parts.length;
  const wildcard = usable.filter((item) => WILDCARD_CHARS.test(item.zipPath));
  pack(wildcard, WILDCARD_PART_BYTES);

  return {
    parts,
    regularParts,
    oversized,
    wildcardTooBig,
    wildcardCount: wildcard.length,
    duplicates: getTotalFileCount() - items.length,
  };
}

// Replace wildcard characters muOS cannot verify in large archives
function renameWildcardFiles() {
  Object.entries(state.files).forEach(([category, files]) => {
    files.forEach((fileData) => {
      fileData.relativePath = fileData.relativePath
        .replace(/\[/g, "(")
        .replace(/\]/g, ")")
        .replace(/[*?]/g, "_");
    });
    const zone = document.querySelector(
      `.upload-zone[data-category="${category}"]`,
    );
    renderFileList(category, zone.parentElement.querySelector(".file-list"));
  });
  updatePreview();
  updateGenerateButton();
}

function removeOversizedFiles() {
  Object.entries(state.files).forEach(([category, files]) => {
    state.files[category] = files.filter(
      (f) => f.size <= ARCHIVE_LIMITS.maxEntryBytes,
    );
    const zone = document.querySelector(
      `.upload-zone[data-category="${category}"]`,
    );
    renderFileList(category, zone.parentElement.querySelector(".file-list"));
  });
  updatePreview();
  updateGenerateButton();
  updateRomSystemInfo();
}

function renderArchiveNotices(plan) {
  const notices = document.getElementById("archive-notices");
  const html = [];

  if (plan.oversized.length > 0) {
    html.push(`<div class="error-message">
      <p class="font-semibold mb-1">${plan.oversized.length} file(s) are over muOS's 512 MB per-file limit.</p>
      <p>muOS rejects any archive that contains them. Copy these straight to the SD card instead, or convert disc images to CHD.</p>
      <ul class="mt-2 font-mono text-xs">${plan.oversized
        .slice(0, 5)
        .map((i) => `<li>${escapeHtml(i.zipPath)} (${formatBytes(i.fileData.size)})</li>`)
        .join("")}${plan.oversized.length > 5 ? "<li>…</li>" : ""}</ul>
      <button id="remove-oversized-btn" class="notice-btn mt-3">Remove oversized files</button>
    </div>`);
  }

  if (plan.wildcardTooBig.length > 0) {
    html.push(`<div class="error-message">
      <p class="font-semibold mb-1">${plan.wildcardTooBig.length} file(s) over 128 MB have [ ] * or ? in their names.</p>
      <p>muOS can't verify large files with these characters in their names. Rename them to install them in a .muxupd.</p>
      <button class="notice-btn rename-wildcard-btn mt-3">Replace [ ] with ( ) in file names</button>
    </div>`);
  } else if (plan.wildcardCount > 0) {
    html.push(`<div class="info-message">
      <p>${plan.wildcardCount} file(s) have [ ] * or ? in their names. muOS can only verify these in small updates, so they go into separate archives of up to 128 MB.</p>
      <button class="notice-btn rename-wildcard-btn mt-2">Replace [ ] with ( ) instead</button>
    </div>`);
  }

  if (plan.parts.length > 1) {
    const reasons = [];
    if (plan.regularParts > 1) {
      reasons.push("it is over muOS's 2 GB / 16,384 file limit per archive");
    }
    if (plan.parts.length > plan.regularParts && plan.regularParts > 0) {
      reasons.push("files with [ ] * or ? in their names need their own small archives");
    }
    html.push(`<div class="warning-message">
      This content will be split into <strong>${plan.parts.length} .muxupd files</strong>${reasons.length ? ` because ${reasons.join(" and ")}` : ""}.
      Install each one from the Archive Manager. Your browser may ask permission to download multiple files.
    </div>`);
  }

  if (plan.duplicates > 0) {
    html.push(`<div class="warning-message">${plan.duplicates} file(s) share a path with another file and will be skipped.</div>`);
  }

  if (state.files.config.length > 0) {
    html.push(`<div class="info-message">RetroArch configs are installed to <span class="font-mono">/opt/muos/share/info/config</span> on the system partition, whichever SD card you selected.</div>`);
  }

  notices.innerHTML = html.join("");

  const removeBtn = document.getElementById("remove-oversized-btn");
  if (removeBtn) removeBtn.addEventListener("click", removeOversizedFiles);
  notices.querySelectorAll(".rename-wildcard-btn").forEach((btn) => {
    btn.addEventListener("click", renameWildcardFiles);
  });
}

// Preview tree generation
function updatePreview() {
  const previewTree = document.getElementById("preview-tree");
  const totalFiles = document.getElementById("total-files");
  const totalSize = document.getElementById("total-size");
  const totalParts = document.getElementById("total-parts");

  const fileCount = getTotalFileCount();
  const fileSize = getTotalFileSize();
  const plan = planArchives();

  totalFiles.textContent = fileCount;
  totalSize.textContent = formatBytes(fileSize);
  totalParts.textContent = plan.parts.length;
  renderArchiveNotices(plan);

  if (fileCount === 0) {
    previewTree.innerHTML =
      '<p class="text-gray-500 italic">No files added yet...</p>';
    return;
  }

  // Build tree structure
  const tree = {};

  // Add files to tree
  Object.entries(state.files).forEach(([category, files]) => {
    files.forEach((fileData) => {
      addToTree(
        tree,
        getZipPath(category, fileData)
          .split("/")
          .filter((p) => p),
      );
    });
  });
  addToTree(tree, [MANIFEST_NAME]);

  previewTree.innerHTML = renderTree(tree);
}

function addToTree(tree, pathParts) {
  if (pathParts.length === 0) return;

  const [current, ...rest] = pathParts;

  if (!tree[current]) {
    tree[current] = rest.length === 0 ? null : {};
  }

  if (rest.length > 0 && tree[current] !== null) {
    addToTree(tree[current], rest);
  }
}

function renderTree(tree, indent = 0) {
  let html = "";
  const entries = Object.entries(tree).sort(([a], [b]) => {
    // Folders first, then files
    const aIsFolder = tree[a] !== null;
    const bIsFolder = tree[b] !== null;
    if (aIsFolder && !bIsFolder) return -1;
    if (!aIsFolder && bIsFolder) return 1;
    return a.localeCompare(b);
  });

  entries.forEach(([name, children]) => {
    const isFolder = children !== null;
    const icon = isFolder ? "📁" : "📄";
    const className = isFolder ? "tree-folder" : "tree-file";
    const indentStr = "  ".repeat(indent);

    html += `<div class="${className}">${indentStr}${icon} ${escapeHtml(name)}</div>`;

    if (isFolder && children) {
      html += renderTree(children, indent + 1);
    }
  });

  return html;
}

// Generate .muxupd file
function updateGenerateButton() {
  const generateBtn = document.getElementById("generate-btn");
  const plan = planArchives();
  const blocked = plan.oversized.length > 0 || plan.wildcardTooBig.length > 0;
  generateBtn.disabled = plan.parts.length === 0 || blocked;
  generateBtn.textContent =
    plan.parts.length > 1
      ? `Generate ${plan.parts.length} .muxupd Files`
      : "Generate .muxupd File";
}

// Stream a file through an incremental hash-wasm hasher
async function hashFile(file, createHasher, onBytes) {
  const hasher = await createHasher();
  hasher.init();
  const reader = file.stream().getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    hasher.update(value);
    if (onBytes) onBytes(value.length);
  }
  return hasher.digest("hex");
}

// Write one archive. muOS (2606.0+) checks every file against manifest.sha256
// before installing, and warns or refuses if it is missing or doesn't match.
async function writeArchive(part, filename, onBytes) {
  // Create a writable stream to download the file directly to disk
  const fileStream = streamSaver.createWriteStream(filename);

  // STORE only: muOS asks for uncompressed archives, and it rejects entries
  // whose compression ratio is above 1000:1 (e.g. blank save files)
  const zipWriter = new zip.ZipWriter(fileStream, {
    level: 0,
    bufferedWrite: true,
  });

  const manifest = [];
  for (const { fileData, zipPath } of part.items) {
    const hash = await hashFile(fileData.file, hashwasm.createSHA256, onBytes);
    manifest.push(`${hash}  ${zipPath}`);

    // BlobReader streams the file without loading it all into memory
    let added = 0;
    await zipWriter.add(zipPath, new zip.BlobReader(fileData.file), {
      onprogress: (progress) => {
        onBytes(progress - added);
        added = progress;
      },
    });
  }

  await zipWriter.add(
    MANIFEST_NAME,
    new zip.TextReader(manifest.join("\n") + "\n"),
  );

  // Close the ZIP writer (this finalizes the archive and writes it to the stream)
  await zipWriter.close();
}

async function generateMuxupd() {
  const generateBtn = document.getElementById("generate-btn");
  const progress = document.getElementById("progress");
  const progressBar = document.getElementById("progress-bar");
  const progressText = document.getElementById("progress-text");

  const plan = planArchives();
  if (plan.parts.length === 0) return;

  generateBtn.disabled = true;
  progress.classList.remove("hidden");
  progressText.classList.remove("text-red-400", "text-green-400");

  try {
    const timestamp = new Date()
      .toISOString()
      .replace(/[:.]/g, "-")
      .slice(0, -5);
    const total = plan.parts.length;
    const filenames = plan.parts.map((_, i) =>
      total > 1
        ? `Custom_muOS_${timestamp}_part${i + 1}of${total}.muxupd`
        : `Custom_muOS_${timestamp}.muxupd`,
    );

    // Every byte is read twice: once to hash it, once to add it to the archive
    const totalBytes =
      plan.parts.reduce(
        (sum, part) =>
          sum + part.items.reduce((s, i) => s + i.fileData.size, 0),
        0,
      ) * 2;
    let doneBytes = 0;

    for (let i = 0; i < total; i++) {
      const label = total > 1 ? `Archive ${i + 1}/${total}: ` : "";
      progressText.textContent = `${label}Hashing and adding files...`;

      await writeArchive(plan.parts[i], filenames[i], (bytes) => {
        doneBytes += bytes;
        const percent = totalBytes
          ? Math.min(100, Math.round((doneBytes / totalBytes) * 100))
          : 100;
        progressBar.style.width = `${percent}%`;
        progressText.textContent = `${label}Hashing and adding files... ${percent}%`;
      });
    }

    // Success message
    progressBar.style.width = "100%";
    progressBar.classList.remove("bg-muos-yellow");
    progressBar.classList.add("bg-green-500");
    progressText.textContent =
      total > 1
        ? `Success! ${total} archives downloaded.`
        : `Success! ${filenames[0]} downloaded.`;
    progressText.classList.add("text-green-400");

    setTimeout(() => {
      progress.classList.add("hidden");
      progressBar.style.width = "0%";
      progressBar.classList.add("bg-muos-yellow");
      progressBar.classList.remove("bg-green-500");
      progressText.classList.remove("text-green-400");
      updateGenerateButton();
    }, 3000);
  } catch (error) {
    console.error("Error generating .muxupd:", error);
    progressText.textContent = `Error: ${error.message}`;
    progressText.classList.add("text-red-400");
    updateGenerateButton();
  }
}

// Initialize application
document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll(".muos-version").forEach((el) => {
    el.textContent = MUOS_VERSION;
  });

  initSDCardSelection();
  initROMSystemSelection();
  initCatalogueSelection();
  initUploadZones();
  updatePreview();
  updateGenerateButton();

  // Generate button handler
  document
    .getElementById("generate-btn")
    .addEventListener("click", generateMuxupd);
});
