#!/usr/bin/env python3
"""Regenerate systems.js from a checkout of https://github.com/MustardOS/internal

Usage:
    git clone --depth 1 https://github.com/MustardOS/internal.git
    python3 tools/gen-systems.py path/to/internal > systems.js

Reads share/info/manifest/{libretro,external}.json (the same files muOS uses
to auto-assign cores to ROM folders) and config/system/version.
"""
import json
import sys
from pathlib import Path

# Folder name to suggest for popular systems. Every value must appear in that
# system's "friendly" list, otherwise muOS will not auto-assign a core to it.
PREFERRED_FOLDERS = {
    "Arcade": "arcade",
    "Atari 2600": "atari2600",
    "Atari 5200": "atari5200",
    "Atari 7800": "atari7800",
    "Atari Lynx": "lynx",
    "Bandai WonderSwan Color": "wonderswancolor",
    "Commodore Amiga": "amiga",
    "Commodore C64": "c64",
    "Microsoft MSX": "msx",
    "NEC PC Engine": "tg16",
    "NEC PC Engine CD": "pcecd",
    "Nintendo DS": "nds",
    "Nintendo Famicom Disk System": "fds",
    "Nintendo Game Boy": "gb",
    "Nintendo Game Boy Advance": "gba",
    "Nintendo Game Boy Color": "gbc",
    "Nintendo N64": "n64",
    "Nintendo NES - Famicom": "nes",
    "Nintendo SNES - SFC": "snes",
    "PC DOS": "dos",
    "PICO-8": "pico8",
    "SNK Neo Geo": "neogeo",
    "SNK Neo Geo Pocket - Color": "ngpc",
    "ScummVM": "scummvm",
    "Sega 32X": "sega32x",
    "Sega Dreamcast": "dreamcast",
    "Sega Game Gear": "gamegear",
    "Sega Master System": "mastersystem",
    "Sega Mega CD - Sega CD": "segacd",
    "Sega Mega Drive - Genesis": "megadrive",
    "Sega Saturn": "saturn",
    "Sony PlayStation": "psx",
    "Sony PlayStation Portable": "psp",
    "External - Ports": "ports",
    "Apple Macintosh": "macintosh",
    "Atari 800": "atari800",
    "Atari ST-STE-TT-Falcon": "atarist",
    "GCE Vectrex": "vectrex",
    "Galaksija Retro Computer": "galaksija",
    "Handheld Electronic - Game and Watch": "gameandwatch",
    "Media Player": "media",
    "MicroW8": "microw8",
    "Nintendo Pokemon Mini": "pokemini",
    "Nintendo Virtual Boy": "virtualboy",
    "SNK Neo Geo CD": "neogeocd",
    "Sharp X1": "x1",
    "Sinclair ZX Spectrum": "spectrum",
    "Super Mario War": "supermariowar",
    "TIC-80": "tic80",
    "The 3DO Company - 3DO": "3do",
    "Wolfenstein 3D": "wolf3d",
}


def pick_folder(name, friendly):
    preferred = PREFERRED_FOLDERS.get(name)
    if preferred:
        if preferred not in friendly:
            sys.exit(f"Preferred folder '{preferred}' is not a friendly name for '{name}'")
        return preferred
    # Shortest readable name wins; very short ones (ss, gw, ...) are too cryptic
    candidates = sorted(friendly, key=lambda f: (len(f) < 3, len(f), f))
    return candidates[0]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    root = Path(sys.argv[1])
    version = (root / "config/system/version").read_text(encoding="utf-8").strip()

    systems = {}
    for manifest in ("libretro", "external"):
        data = json.loads((root / f"share/info/manifest/{manifest}.json").read_text(encoding="utf-8"))
        for key, entry in data.items():
            system = systems.setdefault(key, {
                "name": entry.get("name") or key,
                "group": entry.get("namespace") or "Other",
                "catalogue": entry.get("catalogue") or key,
                "friendly": [],
                "bios": [],
            })
            for friendly in entry.get("friendly") or []:
                if friendly.lower() not in system["friendly"]:
                    system["friendly"].append(friendly.lower())
            for bios in entry.get("bios") or []:
                item = {"file": bios["file"], "md5": (bios.get("hash") or "").lower()}
                if item not in system["bios"]:
                    system["bios"].append(item)

    output = []
    for key in sorted(systems, key=str.lower):
        system = systems[key]
        if not system["friendly"]:
            continue
        system["folder"] = pick_folder(key, system["friendly"])
        output.append({
            "name": system["name"],
            "group": system["group"],
            "folder": system["folder"],
            "catalogue": system["catalogue"],
            "friendly": system["friendly"],
            "bios": system["bios"],
        })

    code, _, codename = version.partition("_")
    print("// Generated by tools/gen-systems.py from MustardOS/internal - do not edit by hand.")
    print(f"// Source version: {version}")
    print(f"const MUOS_VERSION = {json.dumps(code + ' ' + codename.title())};")
    print()
    print("const MUOS_SYSTEMS = [")
    for system in output:
        print(f"  {json.dumps(system, ensure_ascii=False)},")
    print("];")


if __name__ == "__main__":
    main()
